# Generated by Django 5.0.1 on 2024-03-03 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_tbl_admin_tbl_section_delete_tbl_questions'),
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_section',
        ),
    ]
