# Generated by Django 5.0.1 on 2024-03-04 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0002_delete_tbl_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(max_length=20)),
                ('section_mark', models.IntegerField()),
            ],
        ),
    ]
