# Generated by Django 5.0.1 on 2024-03-08 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_batch_id_tbl_questions_batchdata_and_more'),
        ('Teacher', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_gender', models.CharField(max_length=10)),
                ('student_address', models.TextField()),
                ('student_photo', models.FileField(upload_to='userdocs/')),
                ('student_proof', models.FileField(upload_to='userdocs/')),
                ('student_password', models.CharField(max_length=50, unique=True)),
                ('student_status', models.IntegerField(default=0)),
                ('batchid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batch')),
                ('placeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('subjectid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
