# Generated by Django 5.0.1 on 2024-03-08 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0004_tbl_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_student',
            name='batchid',
        ),
        migrations.RemoveField(
            model_name='tbl_student',
            name='student_photo',
        ),
        migrations.RemoveField(
            model_name='tbl_student',
            name='student_proof',
        ),
        migrations.RemoveField(
            model_name='tbl_student',
            name='subjectid',
        ),
    ]
