# Generated by Django 5.0.1 on 2024-03-09 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0005_remove_tbl_student_batchid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_student',
            name='student_status',
        ),
    ]
