# Generated by Django 5.0.1 on 2024-03-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_batch_id_tbl_questions_batchdata_and_more'),
        ('Teacher', '0007_delete_tbl_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=50)),
                ('student_contact', models.CharField(max_length=15)),
                ('student_email', models.EmailField(max_length=254)),
                ('student_address', models.TextField()),
                ('Student_photo', models.FileField(upload_to='StudentDocs/')),
                ('student_gender', models.CharField(max_length=10)),
                ('student_password', models.CharField(max_length=50, unique=True)),
                ('placeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
            ],
        ),
    ]
