# Generated by Django 5.0.1 on 2024-03-09 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0008_tbl_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_student',
            old_name='Student_photo',
            new_name='student_photo',
        ),
    ]
