# Generated by Django 5.0.1 on 2024-03-09 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_batch_id_tbl_questions_batchdata_and_more'),
        ('Teacher', '0009_rename_student_photo_tbl_student_student_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_date', models.IntegerField()),
                ('exam_status', models.IntegerField(default=0)),
                ('subjectid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
