# Generated by Django 5.0.1 on 2024-03-09 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0010_tbl_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_exam',
        ),
    ]
