# Generated by Django 5.0.1 on 2024-03-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0012_tbl_exam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_exam',
            name='exam_date',
            field=models.DateField(),
        ),
    ]
