# Generated by Django 5.0.1 on 2024-03-11 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_examanswer_tbl_examquestions'),
        ('Teacher', '0013_alter_tbl_exam_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_exam',
            name='batchid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batch'),
        ),
    ]
