# Generated by Django 5.0.1 on 2024-03-04 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_tbl_questions'),
        ('Teacher', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_questions',
            name='section_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_section'),
        ),
        migrations.DeleteModel(
            name='tbl_section',
        ),
    ]
