# Generated by Django 5.0.1 on 2024-03-08 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_tbl_questions_section_id_delete_tbl_section'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_questions',
            old_name='batch_id',
            new_name='batchdata',
        ),
        migrations.RenameField(
            model_name='tbl_questions',
            old_name='section_id',
            new_name='sectiondata',
        ),
        migrations.RenameField(
            model_name='tbl_questions',
            old_name='subject_id',
            new_name='subjectdata',
        ),
    ]
