# Generated by Django 5.0.1 on 2024-03-11 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_rename_batch_id_tbl_questions_batchdata_and_more'),
        ('Teacher', '0013_alter_tbl_exam_exam_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_questions',
            name='exam_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_exam'),
        ),
    ]
