# Generated by Django 5.0.1 on 2024-03-11 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_tbl_examanswer_tbl_examquestions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_examquestions',
        ),
    ]
