# Generated by Django 5.0.1 on 2024-04-05 05:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_delete_tbl_questions'),
        ('Teacher', '0017_tbl_section'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=50)),
                ('batchdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_batch')),
                ('exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_exam')),
                ('sectiondata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_section')),
                ('subjectdata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
