# Generated by Django 5.0.1 on 2024-03-11 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0013_alter_tbl_exam_exam_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=100)),
                ('complaint_reply', models.CharField(max_length=100)),
                ('complaint_status', models.CharField(max_length=100)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_exam')),
            ],
        ),
        migrations.CreateModel(
            name='tbl_review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.IntegerField()),
                ('review_content', models.CharField(max_length=100)),
                ('review_date', models.DateTimeField()),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
