# Generated by Django 5.0.1 on 2024-04-07 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_tbl_answer'),
        ('Teacher', '0019_tbl_student_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_examstudents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_status', models.IntegerField(default=0)),
                ('answer_mark', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.tbl_answer')),
                ('exam_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_exam')),
                ('student_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
