# Generated by Django 5.0.1 on 2024-04-07 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_tbl_examstudents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_examstudents',
            name='answer_mark',
        ),
        migrations.RemoveField(
            model_name='tbl_examstudents',
            name='exam_id',
        ),
        migrations.RemoveField(
            model_name='tbl_examstudents',
            name='student_id',
        ),
        migrations.DeleteModel(
            name='tbl_answer',
        ),
        migrations.DeleteModel(
            name='tbl_examstudents',
        ),
    ]
