# Generated by Django 5.0.1 on 2024-04-07 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_tbl_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_examstudent',
            name='answer_mark',
            field=models.IntegerField(default=0),
        ),
    ]
