# Generated by Django 5.0.1 on 2024-04-07 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_alter_tbl_examstudent_answer_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_answer',
            old_name='examstudents_id',
            new_name='exstudent_id',
        ),
    ]
