# Generated by Django 5.0.1 on 2024-04-10 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_rename_examstudents_id_tbl_answer_exstudent_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_examstudent',
            old_name='exstudent_id',
            new_name='student_id',
        ),
    ]
