# Generated by Django 5.0.1 on 2024-04-12 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0016_rename_answer_mark_tbl_examstudent_total_mark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_examstudent',
            old_name='total_mark',
            new_name='answer_mark',
        ),
    ]
