# Generated by Django 5.0.1 on 2024-04-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0017_rename_total_mark_tbl_examstudent_answer_mark'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tbl_complaint',
        ),
    ]
