# Generated by Django 5.0.1 on 2024-04-15 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0018_delete_tbl_complaint'),
        ('Teacher', '0019_tbl_student_batchid'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_title', models.CharField(max_length=50)),
                ('complaint_content', models.CharField(max_length=100)),
                ('complaint_reply', models.CharField(max_length=100)),
                ('complaint_status', models.CharField(max_length=100)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.tbl_student')),
            ],
        ),
    ]
