# Generated by Django 5.0.1 on 2024-04-16 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0019_tbl_complaint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='exam_id',
        ),
    ]
