# Generated by Django 5.0.1 on 2024-04-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0020_remove_tbl_complaint_exam_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_complaint',
            name='complaint_status',
        ),
        migrations.AddField(
            model_name='tbl_complaint',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
