# Generated by Django 5.0.1 on 2024-03-09 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0012_rename_batch_id_tbl_questions_batchdata_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(max_length=50)),
                ('teacher_contact', models.CharField(max_length=15)),
                ('teacher_email', models.EmailField(max_length=254)),
                ('teacher_password', models.CharField(max_length=50, unique=True)),
                ('teacher_address', models.TextField()),
                ('teacher_photo', models.FileField(upload_to='TeacherDocs/')),
                ('teacher_proof', models.FileField(upload_to='TeacherDocs/')),
                ('teacher_gender', models.CharField(max_length=10)),
                ('place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_place')),
                ('subject_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_subject')),
            ],
        ),
    ]
