# Generated by Django 5.0.1 on 2024-03-09 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbl_teacher',
            name='teacher_status',
            field=models.IntegerField(default=0),
        ),
    ]
